# Generated by Django 4.0 on 2021-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0002_alter_imagetest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='image',
            field=models.ImageField(upload_to='somewhere'),
        ),
    ]
