# Generated by Django 4.0 on 2021-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0003_alter_imagetest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='somewhere'),
        ),
    ]
